version: "3.9"

services:
  api-app:
    build: "./book_server"
    volumes: 
      - "./book_server/static:/book_server/static"
    command: sh -c "python /book_server/manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:5000 book_server.wsgi:application"
  
  api-server:
    image: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./ssu-ai-book-fullchain.pem:/etc/nginx/ssu-ai-book-fullchain.pem"
      - "./ssu-ai-book-private.pem:/etc/nginx/ssu-ai-book-private.pem"
      - "./book_server/static:/usr/share/nginx/static"
  
  ai-app:
    build: "./ai_server"
