# Generated by Django 3.2.6 on 2021-08-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210804_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('review', models.IntegerField()),
                ('description', models.TextField(max_length=1000, null=True)),
                ('price', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=200)),
                ('ratings', models.FloatField()),
                ('genre', models.CharField(max_length=200)),
                ('barcode', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
